//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partition
    {
        public Partition()
        {
            this.Things = new HashSet<Thing>();
            this.CommandTopics = new HashSet<CommandTopic>();
        }
    
        public int Id { get; internal set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string Area { get; internal set; }
        public int MaximumCommandTopic { get; internal set; }
        public Nullable<int> MaximumSubscription { get; internal set; }
        public string Namespace { get; internal set; }
        public string EventStore { get; set; }
        public string Owner { get; internal set; }
        public string OwnerSecret { get; internal set; }
        public string StorageAccount { get; internal set; }
        public string AccessControl { get; internal set; }
        public string AccessControlSecret { get; internal set; }
        public System.DateTime LastUpdated { get; internal set; }
    
        public virtual ICollection<Thing> Things { get; internal set; }
        public virtual ICollection<CommandTopic> CommandTopics { get; internal set; }
    }
}
