ALTER TABLE [kiss].[Neighborhood]
	ADD CONSTRAINT [PK_Neighborhood] 
		PRIMARY KEY CLUSTERED (ClientId ASC)
			WITH (PAD_INDEX = OFF, 
				  STATISTICS_NORECOMPUTE = OFF, 
				  IGNORE_DUP_KEY = OFF, 
				  ALLOW_ROW_LOCKS = ON, 
				  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
